(function MAREJIG_inputModule(windowObject) {
    'use strict';
    var MAREJIG_Groups = windowObject.MAREJIG_Groups;
    var MAREJIG_Scene = windowObject.MAREJIG_Scene;
    var MAREJIG_inputState = { mode: 'idle', pointerId: null, selectedGroupId: null, startScreen: null, lastScreen: null, pendingScreen: null, moved: false, rafId: 0 };
    var MAREJIG_context = { canvas: null, scene: null, renderer: null, callbacks: {}, handlers: null };

    function MAREJIG_getScreenPoint(event) { var rect = MAREJIG_context.canvas.getBoundingClientRect(); return { x: event.clientX - rect.left, y: event.clientY - rect.top }; }
    function MAREJIG_resetState(clearSelection) { if (MAREJIG_inputState.rafId) windowObject.cancelAnimationFrame(MAREJIG_inputState.rafId); Object.assign(MAREJIG_inputState, { mode: 'idle', pointerId: null, startScreen: null, lastScreen: null, pendingScreen: null, moved: false, rafId: 0 }); if (clearSelection) { MAREJIG_inputState.selectedGroupId = null; if (MAREJIG_context.scene && MAREJIG_context.scene.ui) MAREJIG_context.scene.ui.selectedGroupId = null; } }
    function MAREJIG_applyPendingMove() { var scene = MAREJIG_context.scene; var screen = MAREJIG_inputState.pendingScreen; MAREJIG_inputState.rafId = 0; if (!scene || !screen || !MAREJIG_inputState.lastScreen) return; var dx = screen.x - MAREJIG_inputState.lastScreen.x; var dy = screen.y - MAREJIG_inputState.lastScreen.y; if (Math.abs(screen.x - MAREJIG_inputState.startScreen.x) + Math.abs(screen.y - MAREJIG_inputState.startScreen.y) > 4) MAREJIG_inputState.moved = true; if (MAREJIG_inputState.mode === 'dragging') { var group = scene.groups[MAREJIG_inputState.selectedGroupId]; if (group) { group.x += dx / scene.camera.zoom; group.y += dy / scene.camera.zoom; MAREJIG_Scene.clampGroupToWorld(scene, group); } } else if (MAREJIG_inputState.mode === 'panning') { scene.camera.x -= dx / scene.camera.zoom; scene.camera.y -= dy / scene.camera.zoom; MAREJIG_Scene.clampCamera(scene); } MAREJIG_inputState.lastScreen = screen; MAREJIG_inputState.pendingScreen = null; if (MAREJIG_context.renderer) MAREJIG_context.renderer.markDirty(MAREJIG_inputState.mode); }
    function MAREJIG_onPointerDown(event) { var scene = MAREJIG_context.scene; if (!scene || (scene.progress && scene.progress.gamePhase !== 'playing')) return; var screen = MAREJIG_getScreenPoint(event); var world = MAREJIG_Scene.screenToWorld(scene, screen); var hit = MAREJIG_Groups.hitTest(scene, world); MAREJIG_inputState.pointerId = event.pointerId; MAREJIG_inputState.startScreen = screen; MAREJIG_inputState.lastScreen = screen; MAREJIG_inputState.pendingScreen = null; MAREJIG_inputState.moved = false; if (hit) { MAREJIG_inputState.mode = 'dragging'; MAREJIG_inputState.selectedGroupId = hit.groupId; if (MAREJIG_Scene.clearInvalidContact) MAREJIG_Scene.clearInvalidContact(scene, hit.groupId); MAREJIG_Groups.bringGroupToFront(scene, hit.groupId); if (windowObject.MAREJIG_Audio) { windowObject.MAREJIG_Audio.unlock(); windowObject.MAREJIG_Audio.playSelect(); } if (MAREJIG_context.callbacks && typeof MAREJIG_context.callbacks.onSelect === 'function') MAREJIG_context.callbacks.onSelect({ groupId: hit.groupId, pieceId: hit.pieceId }); } else { MAREJIG_inputState.mode = 'panning'; MAREJIG_inputState.selectedGroupId = null; scene.ui.selectedGroupId = null; } if (MAREJIG_context.canvas.setPointerCapture) MAREJIG_context.canvas.setPointerCapture(event.pointerId); if (MAREJIG_context.renderer) MAREJIG_context.renderer.markDirty('pointer-down'); event.preventDefault(); }
    function MAREJIG_onPointerMove(event) { if (event.pointerId !== MAREJIG_inputState.pointerId || (MAREJIG_inputState.mode !== 'dragging' && MAREJIG_inputState.mode !== 'panning')) return; MAREJIG_inputState.pendingScreen = MAREJIG_getScreenPoint(event); if (!MAREJIG_inputState.rafId) MAREJIG_inputState.rafId = windowObject.requestAnimationFrame(MAREJIG_applyPendingMove); event.preventDefault(); }
    function MAREJIG_tryHaptic() { var settings = windowObject.MAREJIG_Storage && windowObject.MAREJIG_Storage.getSettings ? windowObject.MAREJIG_Storage.getSettings() : { haptics: true }; if (settings.haptics !== false && windowObject.navigator && typeof windowObject.navigator.vibrate === 'function') windowObject.navigator.vibrate(12); }
    function MAREJIG_onPointerUp(event) { var scene = MAREJIG_context.scene; if (!scene || event.pointerId !== MAREJIG_inputState.pointerId) return; if (MAREJIG_inputState.rafId) { windowObject.cancelAnimationFrame(MAREJIG_inputState.rafId); MAREJIG_applyPendingMove(); } var mode = MAREJIG_inputState.mode; var groupId = MAREJIG_inputState.selectedGroupId; var moved = MAREJIG_inputState.moved; var candidate = null; var merged = null; if (mode === 'dragging' && moved && groupId && scene.groups[groupId]) { scene.progress.startedAt = scene.progress.startedAt || Date.now(); scene.progress.moves += 1; MAREJIG_Groups.recalculateGroupBounds(scene, groupId); candidate = MAREJIG_Groups.findSnapCandidate(scene, groupId, { isTouch: event.pointerType !== 'mouse' }); if (candidate) { var previousIds = [candidate.sourceGroupId, candidate.targetGroupId]; merged = MAREJIG_Groups.applySnap(scene, groupId, candidate); if (merged) { MAREJIG_Scene.clampGroupToWorld(scene, merged); if (MAREJIG_Scene.clearInvalidContact) MAREJIG_Scene.clearInvalidContact(scene); if (MAREJIG_Scene.resolveAllPassiveOverlaps) MAREJIG_Scene.resolveAllPassiveOverlaps(scene, { draggingGroupId: merged.id, limit: 2 }); if (windowObject.MAREJIG_Segments) windowObject.MAREJIG_Segments.updateMainGroupAfterMerge(scene, merged.id, previousIds); if (windowObject.MAREJIG_Audio) windowObject.MAREJIG_Audio.playSnap(); MAREJIG_tryHaptic(); } } if (!candidate && scene.groups[groupId]) { MAREJIG_Scene.clampGroupToWorld(scene, scene.groups[groupId]); if (MAREJIG_Scene.resolveGroupOverlap) MAREJIG_Scene.resolveGroupOverlap(scene, groupId, { draggingGroupId: null }); if (MAREJIG_Scene.getIncorrectContact && MAREJIG_Scene.markInvalidContact) { var contact = MAREJIG_Scene.getIncorrectContact(scene, groupId); if (contact) MAREJIG_Scene.markInvalidContact(scene, contact.groupId, contact.targetGroupId, { durationMs: 560 }); } } if (MAREJIG_context.callbacks && typeof MAREJIG_context.callbacks.onMoveEnd === 'function') MAREJIG_context.callbacks.onMoveEnd({ moved: moved, groupId: groupId, candidate: candidate, mergedGroupId: merged && merged.id }); } MAREJIG_resetState(true); if (MAREJIG_context.renderer) MAREJIG_context.renderer.markDirty(mode === 'panning' ? 'pan-end' : (candidate ? 'snap' : 'drop')); event.preventDefault(); }
    function MAREJIG_onPointerCancel(event) { if (event.pointerId === MAREJIG_inputState.pointerId) MAREJIG_resetState(true); if (MAREJIG_context.renderer) MAREJIG_context.renderer.markDirty('pointer-cancel'); }
    function MAREJIG_attach(canvas, scene, renderer, callbacks) { MAREJIG_detach(); Object.assign(MAREJIG_context, { canvas: canvas, scene: scene, renderer: renderer, callbacks: callbacks || {} }); MAREJIG_context.handlers = { pointerdown: MAREJIG_onPointerDown, pointermove: MAREJIG_onPointerMove, pointerup: MAREJIG_onPointerUp, pointercancel: MAREJIG_onPointerCancel }; Object.keys(MAREJIG_context.handlers).forEach(function MAREJIG_addHandler(name) { canvas.addEventListener(name, MAREJIG_context.handlers[name]); }); canvas.style.touchAction = 'none'; return MAREJIG_Input; }
    function MAREJIG_detach() { if (MAREJIG_context.canvas && MAREJIG_context.handlers) Object.keys(MAREJIG_context.handlers).forEach(function MAREJIG_removeHandler(name) { MAREJIG_context.canvas.removeEventListener(name, MAREJIG_context.handlers[name]); }); Object.assign(MAREJIG_context, { canvas: null, scene: null, renderer: null, callbacks: {}, handlers: null }); MAREJIG_resetState(false); }
    function MAREJIG_setScene(scene) { MAREJIG_context.scene = scene; MAREJIG_resetState(false); }
    function MAREJIG_cancelInteraction() { MAREJIG_resetState(true); }
    var MAREJIG_Input = Object.freeze({ attach: MAREJIG_attach, detach: MAREJIG_detach, setScene: MAREJIG_setScene, cancelInteraction: MAREJIG_cancelInteraction, state: MAREJIG_inputState });
    windowObject.MAREJIG_Input = MAREJIG_Input;
})(window);
