import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const read = (file) => fs.readFileSync(path.join(root, file), 'utf8');
const css = read('css/marejig.css');
const html = read('index.html');
const menu = read('js/MAREJIG_menu.js');
const main = read('js/MAREJIG_main.js');
const economy = read('js/MAREJIG_economy.js');
const jsFiles = fs.readdirSync(path.join(root, 'js')).filter((file) => file.endsWith('.js'));
const allJs = jsFiles.map((file) => [file, read(`js/${file}`)]);
assert.doesNotMatch(css, /backdrop-filter/i, 'CSS has no backdrop-filter');
assert.doesNotMatch(css, /filter\s*:\s*blur\s*\(/i, 'CSS has no blur filter');
assert.doesNotMatch(css, /animation\s*:[^;]*infinite/i, 'CSS has no permanent animation');
assert.match(css, /@media \(prefers-reduced-motion: reduce\)[\s\S]*\.marejig-juice-dot[\s\S]*animation: none !important/, 'reduced motion disables event decoration');
assert.match(menu, /var showFilters = totalPending > 8;/, 'filters hide for small catalogs');
assert.match(menu, /elements\.filterBar\.hidden = !showFilters;/, 'filter visibility is updated');
assert.match(menu, /'Normal'/, 'difficulty uses playful Normal label');
assert.doesNotMatch(html, /12×9|16×12|24–60 piezas|Love Arcade · Jigsaw|premium con piezas ortogonales/, 'normal markup does not expose technical menu copy');
const gameMarkup = html.slice(html.indexOf('id="marejig-screen-game"'), html.indexOf('id="marejig-screen-error"'));
assert.match(gameMarkup, /marejig-game-overlay/, 'gameplay keeps compact overlay');
assert.doesNotMatch(gameMarkup, />[^<]*(Tiempo|Movimientos|Imagen cargada|runtime|seed|generador|RC|piezas)[^<]*</i, 'gameplay markup keeps technical text hidden');
assert.match(main, /Array\.from\(\{ length: 8 \}\)/, 'snap effect is capped at eight particles');
assert.match(main, /Array\.from\(\{ length: 12 \}\)/, 'victory effect is capped at twelve stars');
assert.match(main, /if \(MAREJIG_getReducedMotion\(\)\) return;/, 'event juice respects reduced motion');
assert.doesNotMatch(main, /requestAnimationFrame\([^)]*MAREJIG_play(?:SnapJuice|VictoryStars)/, 'juice does not create a render loop');
assert.equal(allJs.filter(([, source]) => /\bcompleteLevel\s*\(/.test(source)).map(([file]) => file).join(','), 'MAREJIG_economy.js', 'completeLevel remains isolated to economy');
assert.match(economy, /GameCenter\.completeLevel/, 'economy integration still reports completeLevel');
assert.match(html, /<script src="\.\.\/\.\.\/js\/app\.js"><\/script>\s*<\/body>/, 'app.js remains the last script');
assert.equal(allJs.some(([, source]) => /windowObject\.(?:GameCenter|ECONOMY|THEMES)\s*=/.test(source)), false, 'forbidden globals are not assigned');
assert.equal(allJs.some(([, source]) => /\b(?:CONFIG|ECONOMY|THEMES)\s*=/.test(source)), false, 'forbidden bare declarations are absent');
console.log('phase12 visual juice audit tests ok');
