import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const read = (file) => fs.readFileSync(path.join(root, file), 'utf8');
const html = read('index.html');
const css = read('css/marejig.css');
const main = read('js/MAREJIG_main.js');
const state = read('js/MAREJIG_state.js');
const sources = fs.readdirSync(path.join(root, 'js')).filter((file) => file.endsWith('.js')).map((file) => [file, read(path.join('js', file))]);
const allJs = sources.map(([, source]) => source).join('\n');

assert.match(state, /appPhase:\s*'menu'/, 'state exposes an application phase');
assert.match(main, /currentScreen:\s*name, appPhase:\s*name/, 'screen changes update the visible app phase');
assert.match(main, /MAREJIG_PREPARING_MIN_VISIBLE_MS\s*=\s*1350/, 'preparing has a standard minimum visible duration');
assert.match(main, /MAREJIG_PREPARING_READY_HOLD_MS\s*=\s*620/, 'ready state has a deliberate completion hold');
assert.match(html, /class="marejig-screen marejig-preparing" id="marejig-screen-preparing"/, 'preparing screen exists');
assert.match(html, /id="marejig-screen-preparing"[\s\S]*aria-live="polite"[\s\S]*aria-busy="true"/, 'preparing screen politely announces busy state');
assert.match(html, /id="marejig-preparing-step">Cortando imagen…<\/p>/, 'preparing has visible human loading copy');
assert.match(html, /data-marejig-step="image"[\s\S]*data-marejig-step="pieces"[\s\S]*data-marejig-step="scene"[\s\S]*data-marejig-step="ready"/, 'preparing has four staged progress segments');
assert.match(html, /id="marejig-preparing-retry"[\s\S]*Reintentar/, 'preparing error state has retry action');
assert.match(main, /MAREJIG_showScreen\('preparing'\)[\s\S]*MAREJIG_ImageLoader\.loadPlayableImage/, 'level selection shows preparing before image loading');
assert.match(main, /MAREJIG_setPreparingStage\('ready'\)[\s\S]*MAREJIG_Renderer\.setScene\(scene\)[\s\S]*MAREJIG_Renderer\.render\(\)[\s\S]*MAREJIG_finishPreparingToGame\(\)/, 'gameplay reveal waits for scene setup and first render');
assert.match(main, /Math\.max\(minimumWait, readyHold\)/, 'fast level loads still hold the completed preparing beat');
assert.match(main, /marejig-preparing-ready/, 'ready state adds a visual completion class');
assert.match(main, /screen === 'game' && \(preparing \|\| playing\)/, 'game screen can initialize behind the preparing cover');
assert.match(css, /\.marejig-is-preparing #marejig-screen-game\s*\{\s*pointer-events:\s*none;/, 'game input is blocked while preparing');
assert.match(main, /MAREJIG_clearPreparingTimer\(\)[\s\S]*MAREJIG_showScreen\('playing'\)/, 'preparing timer is cleared before gameplay is revealed');
assert.match(main, /MAREJIG_preparingRevealTimerId[\s\S]*clearTimeout/, 'pending reveal timers are cleaned up');
assert.match(main, /MAREJIG_showPreparingError\(\)/, 'fatal preparation errors stay on the friendly preparing surface');
assert.match(main, /No pudimos preparar este puzzle/, 'preparing error copy is friendly');
assert.doesNotMatch(html.slice(html.indexOf('id="marejig-screen-preparing"'), html.indexOf('id="marejig-screen-game"')), /seed|runtime|board|Cloudinary|imagen cargada|\d+\s*piezas/i, 'preparing markup omits technical copy and counts');
assert.doesNotMatch(css, /backdrop-filter|filter\s*:\s*blur\s*\(/, 'preparing CSS avoids backdrop filters and blur');
assert.doesNotMatch(css, /\.marejig-preparing[\s\S]*animation\s*:[^;]*infinite/, 'preparing animations are not infinite');
assert.match(css, /@media \(prefers-reduced-motion: reduce\)[\s\S]*\.marejig-preparing-preview-shine,[\s\S]*\.marejig-loader-piece,[\s\S]*animation:\s*none !important/, 'reduced motion disables preparing animations');
assert.match(css, /@keyframes marejig-piece-snap-a[\s\S]*transform:[\s\S]*opacity:/, 'piece animation uses transform and opacity');
assert.match(css, /marejig-preparing-ready-pop[\s\S]*transform:/, 'ready beat uses transform-only polish');
assert(html.lastIndexOf('../../js/app.js') > html.lastIndexOf('MAREJIG_main.js'), '../../js/app.js remains the final script');
assert.equal((read('js/MAREJIG_economy.js').match(/completeLevel\s*\(/g) || []).length, 1, 'economy owns the only completeLevel call');
sources.filter(([file]) => file !== 'MAREJIG_economy.js').forEach(([file, source]) => assert.doesNotMatch(source, /completeLevel\s*\(/, `${file} must not define or call completeLevel`));
assert.doesNotMatch(allJs, /window(?:Object)?\.(?:GameCenter|ECONOMY|THEMES)\s*=/, 'scripts do not assign forbidden globals');
assert.doesNotMatch(allJs, /\b(?:CONFIG|ECONOMY|THEMES)\s*=/, 'scripts do not declare forbidden unnamespaced identifiers');
console.log('phase15 preparing unit tests ok');
