import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const read = (file) => fs.readFileSync(path.join(root, file), 'utf8');
const html = read('index.html');
const css = read('css/marejig.css');
const main = read('js/MAREJIG_main.js');
const storage = read('js/MAREJIG_storage.js');
const sources = fs.readdirSync(path.join(root, 'js')).filter((file) => file.endsWith('.js')).map((file) => [file, read(path.join('js', file))]);
const allJs = sources.map(([, source]) => source).join('\n');
const activeModal = html.match(/<div class="marejig-modal" id="marejig-active-save-modal"[\s\S]*?<\/div>\s*<div class="marejig-modal" id="marejig-help-modal"/)?.[0] || '';
const startLevel = main.slice(main.indexOf('function MAREJIG_startLevel'), main.indexOf('function MAREJIG_showPreparingError'));

assert.doesNotMatch(allJs, /\b(?:windowObject|window)\.(?:confirm|alert|prompt)\s*\(/, 'scripts never call native browser dialogs through window');
assert.doesNotMatch(allJs, /(^|[^\w.])(?:confirm|alert|prompt)\s*\(/, 'scripts never call unqualified native browser dialogs');
assert.match(activeModal, /role="dialog" aria-modal="true" aria-labelledby="marejig-active-save-title" aria-describedby="marejig-active-save-copy"/, 'active save choice uses an accessible modal dialog');
assert.match(activeModal, /Tienes una partida en curso/, 'modal title is direct and short');
assert.match(activeModal, /Empezar[\s\S]*reemplazará ese progreso/, 'modal copy clearly explains the consequence once');
assert.equal((activeModal.match(/<button /g) || []).length, 3, 'modal exposes exactly three actions');
assert.match(activeModal, /id="marejig-active-save-continue"[^>]*>Continuar partida<\/button>/, 'primary action continues the saved puzzle');
assert.match(activeModal, /id="marejig-active-save-replace"[^>]*>Empezar nuevo<\/button>/, 'warning action starts the selected puzzle');
assert.match(activeModal, /id="marejig-active-save-cancel"[^>]*>Cancelar<\/button>/, 'secondary action cancels without side effects');
assert.match(main, /function MAREJIG_shouldOfferActiveSaveChoice\(activeSave, selectedLevelId\)[\s\S]*var selectedLevelCompleted = MAREJIG_Storage\.isLevelCompleted\(selectedLevelId\);[\s\S]*activeSave && activeSave\.levelId !== selectedLevelId && !selectedLevelCompleted/, 'different incomplete selected levels open the custom modal');
assert.match(startLevel, /MAREJIG_showActiveSaveChoiceModal\(active, level, \{[\s\S]*onContinue:[\s\S]*onReplace:[\s\S]*onCancel:/, 'modal receives active save, selected level and action callbacks');
assert.match(startLevel, /MAREJIG_showActiveSaveChoiceModal[\s\S]*return;/, 'selected level loading waits until the user chooses an action');
assert.match(main, /function MAREJIG_continueActiveSaveChoice\(\)[\s\S]*MAREJIG_startLevel\(activeLevelId, \{ resume: true \}\)/, 'Continuar partida resumes the active save');
assert.match(main, /function MAREJIG_replaceActiveSaveChoice\(\)[\s\S]*MAREJIG_startLevel\(selectedLevelId, \{ forceNew: true \}\)/, 'Empezar nuevo replaces the active save in one step');
assert.match(startLevel, /if \(options && options\.forceNew\) \{[\s\S]*MAREJIG_Storage\.clearActiveSave\(\);[\s\S]*MAREJIG_Storage\.clearLevelProgress\(levelId\);/, 'active save is cleared only after the destructive action');
assert.match(main, /function MAREJIG_cancelActiveSaveChoice\(\)[\s\S]*MAREJIG_closeActiveSaveChoiceModal\(\)/, 'Cancelar only closes the choice modal');
assert.match(main, /MAREJIG_openModal\('marejig-active-save-modal', 'marejig-active-save-continue'\)/, 'the primary action receives focus on open');
assert.match(main, /MAREJIG_trapModalFocus\(event\)/, 'keyboard focus stays inside open modals');
assert.match(main, /event\.key !== 'Escape'[\s\S]*marejig-active-save-modal'[\s\S]*MAREJIG_cancelActiveSaveChoice\(\)/, 'Escape cancels the active save modal');
assert.match(main, /if \(MAREJIG_lastFocus && MAREJIG_lastFocus\.focus\) MAREJIG_lastFocus\.focus\(\);/, 'closing a modal restores focus to its opener');
assert.match(storage, /if \(save && !valid\) \{[\s\S]*MAREJIG_clearActiveSave\(\);/, 'corrupt active saves are safely cleaned without showing the modal');
assert.match(css, /\.marejig-active-save-card \{[\s\S]*background: #132443;[\s\S]*box-shadow:/, 'custom modal uses a solid game-styled panel');
assert.match(css, /\.marejig-active-save-actions \{[\s\S]*grid-template-columns: 1fr;[\s\S]*gap: 9px;/, 'actions are mobile-first and touch friendly');
assert.match(css, /\.marejig-button-warning \{[\s\S]*border-color: rgba\(255, 141, 146, 0\.44\);/, 'destructive action has a moderate warning style');
assert.match(css, /@keyframes marejig-dialog-enter[\s\S]*opacity[\s\S]*transform/, 'modal entrance animates only opacity and transform');
assert.match(css, /@media \(prefers-reduced-motion: reduce\)[\s\S]*\.marejig-active-save-card \{[\s\S]*animation: none;/, 'reduced motion disables the modal entrance animation');
assert.doesNotMatch(css, /backdrop-filter|filter\s*:\s*blur\s*\(|blur\(/i, 'CSS avoids glassmorphism and blur effects');
assert.doesNotMatch(css, /animation\s*:[^;]*infinite/i, 'CSS avoids infinite animations');
assert.match(html, /<script src="\.\.\/\.\.\/js\/app\.js"><\/script>\s*<\/body>/, '../../js/app.js remains the final script');
assert.equal((read('js/MAREJIG_economy.js').match(/completeLevel\s*\(/g) || []).length, 1, 'completeLevel remains owned by MAREJIG_economy.js');
sources.filter(([file]) => file !== 'MAREJIG_economy.js').forEach(([file, source]) => assert.doesNotMatch(source, /completeLevel\s*\(/, `${file} must not define or call completeLevel`));
assert.doesNotMatch(allJs, /window(?:Object)?\.(?:GameCenter|ECONOMY|THEMES)\s*=/, 'forbidden window globals remain absent');
assert.doesNotMatch(allJs, /\b(?:CONFIG|ECONOMY|THEMES)\s*=/, 'forbidden unnamespaced declarations remain absent');

console.log('phase16 active save modal unit tests ok');
