import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const read = (file) => fs.readFileSync(path.join(root, file), 'utf8');
const html = read('index.html');
const css = read('css/marejig.css');
const main = read('js/MAREJIG_main.js');
const state = read('js/MAREJIG_state.js');
const sources = fs.readdirSync(path.join(root, 'js')).filter((file) => file.endsWith('.js')).map((file) => [file, read(path.join('js', file))]);
const allJs = sources.map(([, source]) => source).join('\n');

assert.match(state, /appPhase:\s*'menu'/, 'state exposes an application phase');
assert.match(main, /currentScreen:\s*name, appPhase:\s*name/, 'screen changes update the visible app phase');
assert.match(main, /MAREJIG_PREPARING_MIN_VISIBLE_MS\s*=\s*5000/, 'preparing has a five second minimum visible duration');
assert.match(main, /MAREJIG_PREPARING_PROGRESS_TICK_MS\s*=\s*250/, 'preparing placebo progress updates at a controlled cadence');
assert.match(main, /Math\.min\(99, \(elapsed \/ MAREJIG_PREPARING_MIN_VISIBLE_MS\) \* 99\)/, 'placebo progress can advance past 96 before reveal');
assert.match(html, /class="marejig-screen marejig-preparing" id="marejig-screen-preparing"/, 'preparing screen exists');
assert.match(html, /id="marejig-screen-preparing"[\s\S]*aria-live="polite"[\s\S]*aria-busy="true"/, 'preparing screen politely announces busy state');
assert.match(html, /id="marejig-preparing-step">Cortando imagen…<\/p>/, 'preparing has visible human loading copy');
assert.match(html, /id="marejig-preparing-percent">0%<\/strong>/, 'preparing exposes a visual placebo percentage');
assert.match(html, /marejig-preparing-progress-fill/, 'preparing includes a premium progress fill');
assert.doesNotMatch(html, /marejig-preparing-steps|data-marejig-step="(?:image|pieces|scene|ready)"/, 'preparing omits labels below the progress bar');
assert.match(html, /id="marejig-preparing-retry"[\s\S]*Reintentar/, 'preparing error state has retry action');
assert.match(main, /MAREJIG_showScreen\('preparing'\)[\s\S]*MAREJIG_ImageLoader\.loadPlayableImage/, 'level selection shows preparing before image loading');
assert.match(main, /MAREJIG_Renderer\.setScene\(scene\)[\s\S]*MAREJIG_Renderer\.render\(\)[\s\S]*MAREJIG_finishPreparingToGame\(\)/, 'gameplay reveal waits for scene setup and first render');
assert.match(main, /Math\.max\(0, MAREJIG_PREPARING_MIN_VISIBLE_MS - elapsed\)/, 'fast level loads wait until the five second minimum has elapsed');
assert.doesNotMatch(main, /READY_HOLD_MS/, 'loads that exceed the minimum do not wait for an extra ready hold');
assert.match(main, /if \(progress >= 100\) return 'ready'/, 'ready stage is reserved for the final 100 percent reveal');
assert.match(main, /MAREJIG_updatePreparingMeter\(100\)[\s\S]*MAREJIG_setPreparingStage\('ready'\)/, 'progress reaches 100 only when reveal begins');
assert.match(main, /marejig-preparing-ready/, 'ready state adds a visual completion class');
assert.doesNotMatch(main, /querySelectorAll\('\.marejig-preparing-segment'\)/, 'preparing no longer manages removed stage labels');
assert.match(main, /screen === 'game' && \(preparing \|\| playing\)/, 'game screen can initialize behind the preparing cover');
assert.match(css, /\.marejig-is-preparing #marejig-screen-game,[\s\S]*\.marejig-is-preparing \.marejig-game-overlay\s*\{\s*pointer-events:\s*none;/, 'game input is blocked while preparing');
assert.match(main, /MAREJIG_clearPreparingTimer\(\)[\s\S]*MAREJIG_showScreen\('playing'\)/, 'preparing timer is cleared before gameplay is revealed');
assert.match(main, /MAREJIG_preparingRevealTimerId[\s\S]*clearTimeout/, 'pending reveal timers are cleaned up');
assert.match(main, /MAREJIG_updatePreparingMeter[\s\S]*style\.setProperty\('--marejig-preparing-progress'/, 'placebo meter updates CSS progress state');
assert.match(main, /MAREJIG_showPreparingError\(\)/, 'fatal preparation errors stay on the friendly preparing surface');
assert.match(main, /No pudimos preparar este puzzle/, 'preparing error copy is friendly');
assert.doesNotMatch(html.slice(html.indexOf('id="marejig-screen-preparing"'), html.indexOf('id="marejig-screen-game"')), /seed|runtime|board|Cloudinary|imagen cargada|\d+\s*piezas/i, 'preparing markup omits technical copy and counts');
assert.doesNotMatch(css, /backdrop-filter|filter\s*:\s*blur\s*\(/, 'preparing CSS avoids backdrop filters and blur');
assert.doesNotMatch(css, /\.marejig-preparing[\s\S]*animation\s*:[^;]*infinite/, 'preparing animations are not infinite');
assert.match(css, /@media \(prefers-reduced-motion: reduce\)[\s\S]*\.marejig-preparing-preview-shine,[\s\S]*\.marejig-loader-piece,[\s\S]*animation:\s*none !important/, 'reduced motion disables preparing animations');
assert.match(css, /@keyframes marejig-piece-premium-a[\s\S]*transform:[\s\S]*opacity:/, 'piece animation uses transform and opacity');
assert.match(css, /marejig-preparing-ready-pop[\s\S]*transform:/, 'ready beat uses transform-only polish');
assert.match(css, /marejig-preparing-meter[\s\S]*marejig-preparing-progress-track[\s\S]*marejig-preparing-progress-fill/, 'redesigned loading UI includes a premium meter');
assert.doesNotMatch(css, /marejig-preparing-(?:steps|segment)/, 'CSS omits removed progress labels');
assert(html.lastIndexOf('../../js/app.js') > html.lastIndexOf('MAREJIG_main.js'), '../../js/app.js remains the final script');
assert.equal((read('js/MAREJIG_economy.js').match(/completeLevel\s*\(/g) || []).length, 1, 'economy owns the only completeLevel call');
sources.filter(([file]) => file !== 'MAREJIG_economy.js').forEach(([file, source]) => assert.doesNotMatch(source, /completeLevel\s*\(/, `${file} must not define or call completeLevel`));
assert.doesNotMatch(allJs, /window(?:Object)?\.(?:GameCenter|ECONOMY|THEMES)\s*=/, 'scripts do not assign forbidden globals');
assert.doesNotMatch(allJs, /\b(?:CONFIG|ECONOMY|THEMES)\s*=/, 'scripts do not declare forbidden unnamespaced identifiers');
console.log('phase15 preparing unit tests ok');
