import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const read = (file) => fs.readFileSync(path.join(root, file), 'utf8');
const html = read('index.html');
const css = read('css/marejig.css');
const menu = read('js/MAREJIG_menu.js');
const economy = read('js/MAREJIG_economy.js');
const sources = fs.readdirSync(path.join(root, 'js')).filter((file) => file.endsWith('.js')).map((file) => [file, read(path.join('js', file))]);
const createCard = menu.slice(menu.indexOf('function MAREJIG_createCard'), menu.indexOf('function MAREJIG_setupThumbObserver'));

assert.match(html, /class="marejig-menu-hero"[\s\S]*Elige un puzzle/, 'menu exposes a minimal hero hierarchy');
assert.doesNotMatch(html, /marejig-menu-(?:subtitle|count|kicker)|marejig-total-pending/, 'menu omits subtitle, count and kicker nodes');
assert.doesNotMatch(menu, /pendingTotal|marejig-total-pending|puzzles listos para armar/, 'menu logic no longer renders a puzzle counter');
assert.match(html, /id="marejig-featured-level"[\s\S]*id="marejig-next-levels"/, 'menu separates protagonist and following puzzles');
assert.match(createCard, /documentObject\.createElement\('button'\)/, 'poster cards use native keyboard-operable buttons');
assert.match(createCard, /setAttribute\('aria-label', action \+ ' ' \+ level\.title\)/, 'poster cards expose Jugar or Continuar with title as accessible name');
assert.match(createCard, /class="marejig-action-arrow" aria-hidden="true"><svg[^>]*focusable="false"/, 'poster action arrow uses an accessibility-hidden inline SVG');
assert.match(createCard, /<path d="M5 12h12" \/><path d="M13 6l6 6-6 6" \/>/, 'poster action arrow uses stable SVG paths');
assert.doesNotMatch(createCard, /<span aria-hidden="true">\s*→<\/span>/, 'poster actions omit loose text arrows');
assert.match(html, /class="marejig-exit-link"[^>]*aria-label="Salir al menú principal de Love Arcade"[\s\S]*class="marejig-exit-icon" aria-hidden="true"[\s\S]*<svg[^>]*focusable="false"/, 'exit link keeps an accessible name and uses a hidden inline SVG icon');
assert.doesNotMatch(html, /class="marejig-exit-icon" aria-hidden="true">←<\/span>/, 'exit link omits the loose text arrow');
assert.match(html, /id="marejig-back-to-menu"[^>]*aria-label="Pausar y volver a niveles"[\s\S]*<svg class="marejig-nav-arrow"[^>]*aria-hidden="true"[^>]*focusable="false"/, 'in-game back button keeps an accessible name and uses a hidden inline SVG icon');
assert.doesNotMatch(html + menu, /[←→]|\\u219[02]/, 'navigation and action markup omit loose arrow characters');
assert.match(createCard, /marejig-level-poster-featured[\s\S]*marejig-level-poster-mini/, 'poster creator supports featured and mini card variants');
assert.doesNotMatch(createCard, /rewardCoins|level\.pack|level\.difficulty|currentSegmentIndex|Segmento|monedas|piezas|board/, 'normal menu posters omit technical metadata and chips');
assert.doesNotMatch(html + css + menu, /marejig-filter|setFilters|MAREJIG_FILTER_THRESHOLD/, 'main menu omits filter UI, styles, and logic');
assert.match(menu, /var pendingCount = MAREJIG_menuState\.levels\.length;/, 'pending catalog count comes from the rendered pending-level source of truth');
assert.match(menu, /elements\.empty\.hidden = pendingCount !== 0;/, 'completed catalog state only renders when there are no pending puzzles');
assert.match(css, /\.marejig-level-poster:active\s*\{[^}]*translateY\(1px\) scale\(0\.985\)/, 'poster press feedback is tactile and subtle');
assert.match(css, /@media \(hover: hover\) and \(pointer: fine\)/, 'hover polish is desktop-only');
assert.match(css, /@keyframes marejig-poster-enter[\s\S]*opacity[\s\S]*transform/, 'poster entrance uses compositor-friendly properties');
assert.match(css, /@media \(prefers-reduced-motion: reduce\)[\s\S]*\.marejig-level-poster \{ animation: none; \}/, 'reduced motion disables menu entrances');
assert.match(css, /\.marejig-exit-icon \{[^}]*place-items: center;[^}]*width: 44px;[^}]*height: 44px;/s, 'exit icon is a centered 44px touch-friendly circle');
assert.match(css, /\.marejig-action-arrow \{[^}]*place-items: center;[^}]*width: 28px;[^}]*height: 28px;/s, 'poster action arrow is consistently centered');
assert.match(css, /\.marejig-floating-button \{[^}]*min-width: 44px;[^}]*min-height: 44px;/s, 'floating controls meet the 44px touch target minimum');
assert.doesNotMatch(css, /backdrop-filter|filter\s*:\s*blur\s*\(/, 'CSS contains no glass blur');
assert.doesNotMatch(css, /animation\s*:[^;]*infinite/, 'CSS contains no infinite animation loops');
assert.equal((economy.match(/completeLevel\s*\(/g) || []).length, 1, 'economy retains the only completeLevel call');
sources.filter(([file]) => file !== 'MAREJIG_economy.js').forEach(([file, source]) => assert.doesNotMatch(source, /completeLevel\s*\(/, `${file} must not define or call completeLevel`));
assert(html.lastIndexOf('../../js/app.js') > html.lastIndexOf('MAREJIG_main.js'), '../../js/app.js remains the final script');
assert.doesNotMatch(sources.map(([, source]) => source).join('\n'), /window(?:Object)?\.(?:GameCenter|ECONOMY|THEMES)\s*=/, 'scripts do not assign forbidden globals');
assert.doesNotMatch(sources.map(([, source]) => source).join('\n'), /\b(?:CONFIG|ECONOMY|THEMES)\s*=/, 'scripts do not declare forbidden unnamespaced identifiers');
console.log('phase13 menu redesign unit tests ok');
