import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const read = (file) => fs.readFileSync(path.join(root, file), 'utf8');
const html = read('index.html');
const css = read('css/marejig.css');
const menu = read('js/MAREJIG_menu.js');
const economy = read('js/MAREJIG_economy.js');
const sources = fs.readdirSync(path.join(root, 'js')).filter((file) => file.endsWith('.js')).map((file) => [file, read(path.join('js', file))]);
const createCard = menu.slice(menu.indexOf('function MAREJIG_createCard'), menu.indexOf('function MAREJIG_setupThumbObserver'));

assert.match(html, /class="marejig-menu-hero"[\s\S]*Elige un puzzle[\s\S]*Toca una imagen para empezar\./, 'menu exposes concise playful hierarchy');
assert.match(html, /id="marejig-featured-level"[\s\S]*id="marejig-next-levels"/, 'menu separates protagonist and following puzzles');
assert.match(createCard, /documentObject\.createElement\('button'\)/, 'poster cards use native keyboard-operable buttons');
assert.match(createCard, /setAttribute\('aria-label', action \+ ' ' \+ level\.title\)/, 'poster cards expose Jugar or Continuar with title as accessible name');
assert.match(createCard, /marejig-level-poster-featured[\s\S]*marejig-level-poster-mini/, 'poster creator supports featured and mini card variants');
assert.doesNotMatch(createCard, /rewardCoins|level\.pack|level\.difficulty|currentSegmentIndex|Segmento|monedas|piezas|board/, 'normal menu posters omit technical metadata and chips');
assert.doesNotMatch(html + css + menu, /marejig-filter|setFilters|MAREJIG_FILTER_THRESHOLD/, 'main menu omits filter UI, styles, and logic');
assert.match(menu, /var pendingCount = MAREJIG_menuState\.levels\.length;/, 'pending catalog count comes from the rendered pending-level source of truth');
assert.match(menu, /elements\.empty\.hidden = pendingCount !== 0;/, 'completed catalog state only renders when there are no pending puzzles');
assert.match(css, /\.marejig-level-poster:active\s*\{[^}]*translateY\(1px\) scale\(0\.985\)/, 'poster press feedback is tactile and subtle');
assert.match(css, /@media \(hover: hover\) and \(pointer: fine\)/, 'hover polish is desktop-only');
assert.match(css, /@keyframes marejig-poster-enter[\s\S]*opacity[\s\S]*transform/, 'poster entrance uses compositor-friendly properties');
assert.match(css, /@media \(prefers-reduced-motion: reduce\)[\s\S]*\.marejig-level-poster \{ animation: none; \}/, 'reduced motion disables menu entrances');
assert.doesNotMatch(css, /backdrop-filter|filter\s*:\s*blur\s*\(/, 'CSS contains no glass blur');
assert.doesNotMatch(css, /animation\s*:[^;]*infinite/, 'CSS contains no infinite animation loops');
assert.equal((economy.match(/completeLevel\s*\(/g) || []).length, 1, 'economy retains the only completeLevel call');
sources.filter(([file]) => file !== 'MAREJIG_economy.js').forEach(([file, source]) => assert.doesNotMatch(source, /completeLevel\s*\(/, `${file} must not define or call completeLevel`));
assert(html.lastIndexOf('../../js/app.js') > html.lastIndexOf('MAREJIG_main.js'), '../../js/app.js remains the final script');
assert.doesNotMatch(sources.map(([, source]) => source).join('\n'), /window(?:Object)?\.(?:GameCenter|ECONOMY|THEMES)\s*=/, 'scripts do not assign forbidden globals');
assert.doesNotMatch(sources.map(([, source]) => source).join('\n'), /\b(?:CONFIG|ECONOMY|THEMES)\s*=/, 'scripts do not declare forbidden unnamespaced identifiers');
console.log('phase13 menu redesign unit tests ok');
